config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "schedules#index"
  resources :schedules
  resources :items
  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :schedule_items
  has_many :schedules, through: :schedule_items

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :item_name
  belongs_to_active_hash :status

  with_options presence: true do
    validates :item_name_id, numericality: { other_than: 0 }, uniqueness: true
    validates :status_id, numericality: { other_than: 0 }
  end
end

app/models/item_name.rb
class ItemName < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: 'カメラA' },
    { id: 2, name: 'カメラB' },
    { id: 3, name: 'カメラC' },
    { id: 4, name: 'レンズセットA' },
    { id: 5, name: 'レンズセットB' },
    { id: 6, name: 'レンズセットC' },
    { id: 7, name: '三脚A' },
    { id: 8, name: '三脚B' },
    { id: 9, name: '三脚C' },
    { id: 10, name: 'ミキサーA' },
    { id: 11, name: 'ミキサーB' },
    { id: 12, name: 'ミキサーC' },
    { id: 13, name: 'マイクA' },
    { id: 14, name: 'マイクB' },
    { id: 15, name: 'マイクC' },
    { id: 16, name: '照明セットA' },
    { id: 17, name: '照明セットB' },
    { id: 18, name: '照明セットC' }
  ]
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :schedule_members
  has_many :schedules, through: :schedule_members

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :name
  belongs_to_active_hash :position

  with_options presence: true do
    validates :name_id, numericality: { other_than: 0 }, uniqueness: true
    validates :position_id, numericality: { other_than: 0 }
  end
end

app/models/name.rb
class Name < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '山下 理恵子' },
    { id: 2, name: '森口 いずみ' },
    { id: 3, name: '竹井 信行' },
    { id: 4, name: '大原 浩' },
    { id: 5, name: '西脇 梓' },
    { id: 6, name: '白鳥 尚介' }
  ]
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '撮影' },
    { id: 2, name: '音声' },
    { id: 3, name: 'アシスタント' }
  ]
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  has_many :schedule_items, dependent: :destroy
  has_many :items, through: :schedule_items
  has_many :schedule_members, dependent: :destroy
  has_many :members, through: :schedule_members

  with_options presence: true do
    validates :start_date
    validates :end_date
    validates :client
    validates :title
    validates :content
    validates :items
  end

  # validate :uniqueness_of_same_day

  # def uniqueness_of_same_day
  #   # start_date = @schedule.start_date
  #   # end_date = @schedule.end_date
  #   if Schedule.joins(:schedule_items).exists?()
  #     errors.add(:start_date, "同じ日に使用できません")
  #     false
  #   else
  #     true
  #   end
  # end
end

app/models/schedule_item.rb
class ScheduleItem < ApplicationRecord
  belongs_to :schedule
  belongs_to :item
end

app/models/schedule_member.rb
class ScheduleMember < ApplicationRecord
  belongs_to :schedule
  belongs_to :member
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '問題なし' },
    { id: 2, name: '修理予定' },
    { id: 3, name: '修理中' },
    { id: 4, name: '廃棄予定' },
    { id: 5, name: '廃棄済み' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :schedules
  has_many :items

  with_options presence: true do
    validates :name
    validates :email, uniqueness: true
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]
  before_action :set_items, only: [:show, :edit, :update]

  def index
    @items = Item.all.order(:item_name_id)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path(@item.id)
    else
      render :new
    end
  end

  def show
    @schedules = Schedule.all
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_name_id, :status_id).merge(user_id: current_user.id)
  end

  def set_items
    @item = Item.find(params[:id])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]
  before_action :set_members, only: [:show, :edit, :update]

  def index
    @members = Member.all.order(:name_id)
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to members_path
    else
      render :new
    end
  end

  def show
    @schedules = Schedule.all
  end

  def edit
  end

  def update
    if @member.update(member_params)
      redirect_to members_path
    else
      render :edit
    end
  end

  private

  def member_params
    params.require(:member).permit(:name_id, :position_id)
  end

  def set_members
    @member = Member.find(params[:id])
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to schedule_path(@schedule.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to schedule_path
    else
      render :edit
    end
  end

  def destroy
    @schedule.destroy
    redirect_to root_path
  end

  private

  def schedule_params
    params.require(:schedule).permit(:start_date, :end_date, :client, :title, :content,
                                     { item_ids: [] }, { member_ids: [] }).merge(user_id: current_user.id)
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/items/edit.html.erb
<div class="wrap">
  <div class="h1">
    <h1>機材ステータス 変更</h1>
  </div>

  <div class="form-wrap">
    <%= form_with model: @item, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <%= f.label :item_name %><br/>
        <%= f.collection_select(:item_name_id, ItemName.all, :id, :name, {}, {class:"select-box", id:"item-name"}) %>
      </div>

      <div class="field">
        <%= f.label :status %><br/>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-status"}) %>
      </div>

      <div class="action">
        <%= f.submit "更新", class: "btn-1" %>
      </div>

    <% end %>
  </div>

  <div class="links">
    <%= link_to "Back", item_path, class: "btn-2" %>
  </div>
</div>

app/views/items/index.html.erb
<%= render 'shared/header' %>

<span class="kizairisuto">機材list</span>

<div class="item-lists">
  <div class="box27">
    <span class="box-title">Camera</span>
    <% @items.each do |item| %>
      <% if item.item_name.id <= 9 %>
        <div class="item-list">
          <%= link_to item.item_name.name, item_path(item.id), class: "item-list-name" %>
          <% if item.status.id == 3 %>
            <div class="status-name">
              <%= item.status.name %>
            </div>
          <% else %>
            <%= item.status.name %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="box27">
    <span class="box-title">Audio</span>
    <% @items.each do |item| %>
      <% if (item.item_name.id >= 10) && (item.item_name.id <= 15) %>
        <div class="item-list">
          <%= link_to item.item_name.name, item_path(item.id), class: "item-list-name" %>
          <% if item.status.id == 3 %>
            <div class="status-name">
              <%= item.status.name %>
            </div>
          <% else %>
            <%= item.status.name %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="box27">
    <span class="box-title">Light</span>
    <% @items.each do |item| %>
      <% if item.item_name.id >= 16 %>
        <div class="item-list">
          <%= link_to item.item_name.name, item_path(item.id), class: "item-list-name" %>
          <% if item.status.id == 3 %>
            <div class="status-name">
              <%= item.status.name %>
            </div>
          <% else %>
            <%= item.status.name %>
          <% end %>

        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="wrap">
  <div class="h1">
    <h1>機材登録</h1>
  </div>

  <div class="form-wrap">
    <%= form_with model: @item, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <%= f.label :item_name %><br/>
        <%= f.collection_select(:item_name_id, ItemName.all, :id, :name, {}, {class:"select-box", id:"item-name"}) %>
      </div>

      <div class="field">
        <%= f.label :status %><br/>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-status"}) %>
      </div>

      <div class="action">
        <%= f.submit "登録", class: "btn-1" %>
      </div>

    <% end %>
  </div>

  <div class="links">
    <%= link_to "Back", items_path, class: "btn-2" %>
  </div>
</div>

app/views/items/show.html.erb
<%= render 'shared/header' %>

<span class="kizairisuto">機材持出スケジュール</span>
<span class="item-name">
  <%= @item.item_name.name %>
</span>
<% if user_signed_in? %>
  <%= link_to "編集", edit_item_path, class: "item-edit-tag" %>
<% end %>

<%= month_calendar(attribute: :start_date, end_attribute: :end_date, events: @schedules) do |date, schedules| %>
  <%= date.day %>

  <% schedules.each do |schedule| %>
    <% if schedule.item_ids.include?(@item.id) %>
      <div class="item-schedules-list">
        <%= link_to schedule.title, schedule_path(@item.schedule_ids), class: "item-schedule-title" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manedule</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<div class="wrap">
  <div class="h1">
    <h1>スタッフ編集</h1>
  </div>

  <div class="form-wrap">
    <%= form_with model: @member, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <%= f.label :name %><br/>
        <%= f.collection_select(:name_id, Name.all, :id, :name, {}, {class:"select-box", id:"item-name"}) %>
      </div>

      <div class="field">
        <%= f.label :position %><br/>
        <%= f.collection_select(:position_id, Position.all, :id, :name, {}, {class:"select-box", id:"item-status"}) %>
      </div>

      <div class="action">
        <%= f.submit "更新", class: "btn-1" %>
      </div>

    <% end %>
  </div>

  <div class="links">
    <%= link_to "Back", members_path, class: "btn-2" %>
  </div>
</div>

app/views/members/index.html.erb
<%= render 'shared/header' %>

<span class="kizairisuto">スタッフlist</span>

<div class="item-lists">
  <div class="box27">
    <span class="box-title">撮影</span>
    <% @members.each do |member| %>
      <% if member.position.id == 1 %>
        <div class="member-list">
          <%= link_to member.name.name, member_path(member.id), class: "member-list-name" %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="box27">
    <span class="box-title">音声</span>
    <% @members.each do |member| %>
      <% if member.position.id == 2 %>
        <div class="member-list">
          <%= link_to member.name.name, member_path(member.id), class: "member-list-name" %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="box27">
    <span class="box-title">アシスタント</span>
    <% @members.each do |member| %>
      <% if member.position.id == 3 %>
        <div class="member-list">
          <%= link_to member.name.name, member_path(member.id), class: "member-list-name" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/members/new.html.erb
<div class="wrap">
  <div class="h1">
    <h1>スタッフ登録</h1>
  </div>

  <div class="form-wrap">
    <%= form_with model: @member, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <%= f.label :name %><br/>
        <%= f.collection_select(:name_id, Name.all, :id, :name, {}, {class:"select-box", id:"item-name"}) %>
      </div>

      <div class="field">
        <%= f.label :position %><br/>
        <%= f.collection_select(:position_id, Position.all, :id, :name, {}, {class:"select-box", id:"item-status"}) %>
      </div>

      <div class="action">
        <%= f.submit "登録", class: "btn-1" %>
      </div>

    <% end %>
  </div>

  <div class="links">
    <%= link_to "Back", items_path, class: "btn-2" %>
  </div>
</div>

app/views/members/show.html.erb
<%= render 'shared/header' %>

<span class="kizairisuto">スタッフスケジュール</span>
<span class="member-name">
  <%= @member.name.name %>
</span>
<% if user_signed_in? %>
  <%= link_to "編集", edit_member_path, class: "member-edit-tag" %>
<% end %>

<%= month_calendar(attribute: :start_date, end_attribute: :end_date, events: @schedules) do |date, schedules| %>
  <%= date.day %>

  <% schedules.each do |schedule| %>
    <% if schedule.member_ids.include?(@member.id) %>
      <div class="member-schedules-list">
        <%= link_to schedule.title, schedule_path(@member.schedule_ids), class: "member-schedule-title" %>
      </div>
    <% end %>
  <% end %>

<% end %>

app/views/schedules/edit.html.erb
<div class="wrap">
  <div class="h1">
    <h1>Edit schedule</h1>
  </div>

  <div class="form-wrap">
    <%= form_with model: @schedule, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <%= f.label :start_date %><br/>
        <%= f.date_field :start_date, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :end_date %><br/>
        <%= f.date_field :end_date %>
      </div>

      <div class="field">
        <%= f.label :client %><br/>
        <%= f.text_field :client %>
      </div>

      <div class="field">
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :content %><br/>
        <%= f.text_area :content %>
      </div>

      <div class="field">
        <%= f.label :items %><br/>
        <%= f.collection_check_boxes(:item_ids, Item.where(status_id: [1..2]), :id, :item_name) do |b| %>
          <div class="check-box">
            <%= b.label { b.check_box } + b.text[:name] %>
          </div>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :members %><br/>
        <%= f.collection_check_boxes(:member_ids, Member.all, :id, :name) do |b| %>
          <div class="check-box">
            <%= b.label { b.check_box } + b.text[:name] %>
          </div>
        <% end %>
      </div>

      <div class="action">
        <%= f.submit "更新", class: "btn-1" %>
      </div>

    <% end %>
  </div>

  <div class="links">
    <%= link_to "Back", schedule_path, class: "btn-2" %>
  </div>
</div>

app/views/schedules/index.html.erb
<%= render 'shared/header' %>

<span class="kizairisuto">月間スケジュール</span>

<%= month_calendar(attribute: :start_date, end_attribute: :end_date, events: @schedules) do |date, schedules| %>
  <%= date.day %>

  <% schedules.each do |schedule| %>
    <div class="schedules-list">
      <%= link_to schedule.title, schedule_path(schedule.id), class: "schedule-title" %>
    </div>
  <% end %>
<% end %>

app/views/schedules/new.html.erb
<div class="wrap">
  <div class="h1">
    <h1>New schedule</h1>
  </div>

  <div class="form-wrap">
    <%= form_with model: @schedule, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <%= f.label :start_date %><br/>
        <%= f.date_field :start_date, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :end_date %><br/>
        <%= f.date_field :end_date %>
      </div>

      <div class="field">
        <%= f.label :client %><br/>
        <%= f.text_field :client %>
      </div>

      <div class="field">
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :content %><br/>
        <%= f.text_area :content %>
      </div>

      <div class="field">
        <%= f.label :items %><br/>
        <%= f.collection_check_boxes(:item_ids, Item.where(status_id: [1..2]), :id, :item_name) do |b| %>
          <div class="check-box">
            <%= b.label { b.check_box } + b.text[:name] %>
          </div>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :members %><br/>
        <%= f.collection_check_boxes(:member_ids, Member.all, :id, :name) do |b| %>
          <div class="check-box">
            <%= b.label { b.check_box } + b.text[:name] %>
          </div>
        <% end %>
      </div>

      <div class="action">
        <%= f.submit "登録", class: "btn-1" %>
      </div>

    <% end %>
  </div>

  <div class="links">
    <%= link_to "Back", root_path, class: "btn-2" %>
  </div>
</div>

app/views/schedules/show.html.erb
<%= render 'shared/header' %>

<span class="kizairisuto">スケジュール詳細</span>

<table class="day-table-area">
  <tbody class="day-table">
    <tr>
      <th class="th-size">日付</th>
      <td class="td-size">
        <%= @schedule.start_date.month %>月 <%= @schedule.start_date.day %>日 
        <% if @schedule.end_date != @schedule.start_date %>
          ~ <%= @schedule.end_date.month %>月 <%= @schedule.end_date.day %>日
        <% end %>
      </td>
    </tr>
    <tr>
      <th class="th-size">会社名</th>
      <td class="td-size">
        <%= @schedule.client %>
      </td>
    </tr>
    <tr>
      <th class="th-size">番組名</th>
      <td class="td-size">
        <%= @schedule.title %>
      </td>
    </tr>
    <tr>
      <th class="th-size">内容</th>
      <td class="td-size-content">
        <%= @schedule.content %>
      </td>
    </tr>
    <tr>
      <th class="th-size">使用機材</th>
      <% if @schedule.item_ids %>
        <td class="td-size">
          <% @schedule.items.each do |i| %>
            <%= link_to i.item_name.name, item_path(i), class: "item-show-link" %>
          <% end %>
        </td>
      <% end %>
    </tr>
    <tr>
      <th class="th-size">スタッフ</th>
      <% if @schedule.member_ids %>
        <td class="td-size">
          <% @schedule.members.each do |i| %>
            <%= link_to i.name.name, member_path(i), class: "member-show-link" %>
          <% end %>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>

<div class="edit-link-area">
  <% if user_signed_in? %>
    <%= link_to "編集", edit_schedule_path, class: "edit-link" %>
    <%= link_to "削除", schedule_path(@schedule.id), method: :delete, data: { confirm: "本当に削除しますか?" }, class: "destory-link" %>
  <% end %>
</div>


app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<ul class="nav">
  <div class="nav-start">
    <%= link_to '機材list', items_path, class: "top-btn" %>
    <%= link_to 'スタッフlist', members_path, class: "top-btn" %>
  </div>

  <div class="nav-end">
    <%= link_to 'home', "/", class: "nav-link active" %>
    <% if user_signed_in? %>
      <%= link_to current_user.name, edit_user_registration_path, class: "nav-link active" %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link active" %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class: "nav-link active" %>
      <%= link_to '新規登録', new_user_registration_path, class: "nav-link active" %>
    <% end %>
    <%= link_to 'スケジュール作成', new_schedule_path, class: "nav-link active" %>
  </div>
</ul>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '←'), calendar.url_for_previous_view, class: "calendar-select" %>
    <span class="calendar-title"><%= start_date.year %>年 <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '→'), calendar.url_for_next_view, class: "calendar-select" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>